# Generated by Django 5.1.3 on 2025-12-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ma_khoa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_khoa', models.CharField(max_length=100)),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'khoa',
            },
        ),
    ]
