# Generated by Django 5.1.3 on 2025-12-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('ma_lop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_lop', models.CharField(max_length=50)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_lop', to='khoa.khoa')),
            ],
            options={
                'db_table': 'lop',
            },
        ),
    ]
