# Generated by Django 5.1.3 on 2025-12-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=20)),
                ('hoc_ky', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=20, unique=True)),
                ('ten_mon', models.CharField(max_length=100)),
                ('so_tin_chi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiemRenLuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_ren_luyen', models.IntegerField()),
                ('xep_loai', models.CharField(max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.sinhvien')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketqua.hocky')),
            ],
        ),
        migrations.CreateModel(
            name='DiemHocTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_trung_binh', models.FloatField()),
                ('xep_loai', models.CharField(max_length=50)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.sinhvien')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketqua.hocky')),
            ],
        ),
        migrations.CreateModel(
            name='KetQuaMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_qua_trinh', models.FloatField()),
                ('diem_thi', models.FloatField()),
                ('diem_tong_ket', models.FloatField()),
                ('ket_qua', models.CharField(max_length=20)),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketqua.hocky')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.sinhvien')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketqua.monhoc')),
            ],
        ),
    ]
