# Generated by Django 5.1.3 on 2025-12-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuvantuvan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutuvan',
            name='lich_tu_van',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phieu_tu_van', to='tuvantuvan.lichtuvan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phieutuvan',
            name='ket_qua',
            field=models.TextField(blank=True),
        ),
    ]
