# Generated by Django 5.1.3 on 2025-12-20 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dien_thoai', models.CharField(max_length=15)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_sinh_vien', to='lop.lop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sinh_vien',
            },
        ),
    ]
