# Generated by Django 5.1.3 on 2025-12-20 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khoa', '0001_initial'),
        ('lop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cv', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dien_thoai', models.CharField(max_length=15)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_covan', to='khoa.khoa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'co_van',
            },
        ),
        migrations.CreateModel(
            name='PhanCongCoVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=9)),
                ('hoc_ky', models.IntegerField()),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covan.covan')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lop.lop')),
            ],
            options={
                'db_table': 'phan_cong_cv',
                'unique_together': {('covan', 'lop', 'nam_hoc', 'hoc_ky')},
            },
        ),
    ]
