# Generated by Django 5.1.3 on 2025-12-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covan', '0002_covan_lop_delete_phancongcovan'),
        ('lop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covan',
            name='lop',
        ),
        migrations.CreateModel(
            name='PhanCongCoVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.CharField(max_length=9)),
                ('hoc_ky', models.IntegerField()),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covan.covan')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lop.lop')),
            ],
            options={
                'db_table': 'phan_cong_cv',
                'unique_together': {('covan', 'lop', 'nam_hoc', 'hoc_ky')},
            },
        ),
    ]
