# Generated by Django 5.1.3 on 2025-12-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covan', '0003_remove_covan_lop_phancongcovan'),
        ('lop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covan',
            name='lop',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='covan', to='lop.lop'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhanCongCoVan',
        ),
    ]
