# Generated by Django 5.1.3 on 2025-12-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covan', '0001_initial'),
        ('sinhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichTuVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('dia_diem', models.CharField(max_length=100)),
                ('noi_dung_du_kien', models.TextField()),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covan.covan')),
            ],
            options={
                'db_table': 'lich_tu_van',
            },
        ),
        migrations.CreateModel(
            name='PhieuTuVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField()),
                ('noi_dung_tu_van', models.TextField()),
                ('ket_qua', models.TextField()),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covan.covan')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinhvien.sinhvien')),
            ],
            options={
                'db_table': 'phieu_tu_van',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_danh_gia', models.IntegerField()),
                ('nhan_xet', models.TextField(blank=True)),
                ('phieu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tuvantuvan.phieutuvan')),
            ],
            options={
                'db_table': 'danh_gia',
            },
        ),
    ]
