# Generated by Django 5.1.3 on 2025-12-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuvantuvan', '0002_phieutuvan_lich_tu_van_alter_phieutuvan_ket_qua'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutuvan',
            name='trang_thai',
            field=models.CharField(choices=[('cho_phan_hoi', 'Chờ phản hồi'), ('da_phan_hoi', 'Đã phản hồi'), ('da_huy', 'Đã hủy')], default='cho_phan_hoi', max_length=20),
        ),
    ]
